### ISSUE TITLE
[Feature Request] - Send Cantada

### ISSUE THREAD

**Issue by lucasvillaverde** [julianosirtori/cantadas-app#3]
It would be fine if we have a way to send a cantada to someone.

**Idea:** Share button to share a plain text to social medias or just copy to clipboard. Some future ideas would be sharing a link for a "cantada presentation" page instead of the "generator" page.

**Result**: Be able to send or share a cantada in an easy and fun way. This would increase the engagement of people who use virtual communication tools (social media, live chat, e-mail...)

**Comment by julianosirtori** [comment]
Already exists this functionality, when you click over the cantada, you copy her and can share the cantada
